site_name: Faust
site_description: Faust Programming Language.
copyright: Copyright &copy; 2020 <a href="http://www.grame.fr">Grame-CNCM</a>
nav:
    - Home: index.md
    - Documentation:
        - 'Quick Start' : https://faustdoc.grame.fr/manual/quick-start/
        - 'Faust Language' : https://faustdoc.grame.fr
        - 'Faust Libraries': https://faustlibraries.grame.fr
    - Downloads: downloads.md
    - Tools:
         - 'Faust Web IDE': https://faustide.grame.fr
         - 'Faust Playground': https://faustplayground.grame.fr
         - 'Faust Web Editor': https://fausteditor.grame.fr
    - Community:
        - 'News': community/news.md
        - 'Getting Help': community/help.md
        - 'Reporting Bugs': community/bugs.md
        - 'Faust Conference': community/ifc.md
        - 'Academic Publications': community/publications.md
        - 'Press': community/press.md
        - 'Sponsors': community/sponsors.md
        - 'Made with Faust': community/made-with-faust.md
        - 'Logos': community/logos.md
    - Projects:
        - 'FAST': https://fast.grame.fr
        - 'Amstramgrame': https://amstramgrame.fr/english
    - About: about.md

theme: 
  name: mkdocs
  custom_dir: 'theme'
  navigation_depth: 4

site_dir: ../docs


extra:
    social:
        - type: github
          link: https://github.com/grame-cncm/faust
        - type: home
          link: https://faust.grame.fr
        - type: envelope
          link: mailto:orlarey@grame.fr

plugins:
    - search

#extra_javascript:
#  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full

markdown_extensions:
    - markdown_include.include:
        base_path: './docs'
